import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { Type } from "@sinclair/typebox";
import { homedir } from "os";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { discoverAgents } from "./agents.js";
import { runSingleAgent, runParallel, runChain, mapWithConcurrencyLimit, MAX_CONCURRENCY } from "./subagent.js";
import { loadState, updateState } from "./state.js";
import { microcompactMessages, getCompactionPrompt, formatCompactSummary } from "./compaction.js";
import { convertToLlm, serializeConversation } from "@mariozechner/pi-coding-agent";
import { complete } from "@mariozechner/pi-ai";

// ============================================================
// Workflow State
// ============================================================
// Tracks which phase the agent is in so before_agent_start
// can inject appropriate guidance into the system prompt.
// ============================================================

type WorkflowPhase =
  | "idle"
  | "clarifying"
  | "planning"
  | "ultraplanning";

let currentPhase: WorkflowPhase = "idle";
let activeGoalDocument: string | null = null;

// State file path
const STATE_FILE = join(homedir(), ".pi", "extension-state.json");

export default function (pi: ExtensionAPI) {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const BUNDLED_AGENTS_DIR = join(__dirname, "agents");

  // ============================================================
  // ask_user_question Tool
  // ============================================================
  // The agent calls this autonomously when it encounters ambiguity.
  // The agent generates the question text and choices dynamically.
  // ============================================================

  const DIRECT_INPUT_OPTION = "직접 입력하기";

  const AskUserQuestionParams = Type.Object({
    question: Type.String({
      description: "The question to ask the user. The agent generates this dynamically based on context.",
    }),
    choices: Type.Optional(
      Type.Array(Type.String(), {
        description:
          "Multiple choice options generated by the agent. '직접 입력하기' is auto-appended. Omit for free-text input.",
      })
    ),
    placeholder: Type.Optional(
      Type.String({
        description: "Placeholder hint for free-text input mode.",
      })
    ),
    defaultValue: Type.Optional(
      Type.String({
        description: "Default value if user presses Enter without typing.",
      })
    ),
  });

  pi.registerTool({
    name: "ask_user_question",
    label: "Ask User Question",
    description:
      "Ask the user a question when the agent needs clarification. The agent composes the question and optional choices dynamically. Returns the user's answer as text.",
    promptSnippet:
      "Ask the user a clarifying question with optional multiple-choice answers",
    promptGuidelines: [
      "Use ask_user_question whenever you encounter ambiguity, unclear scope, or need user preference.",
      "Generate the question and choices yourself based on the current context — do not rely on predefined templates.",
      "Offer concrete choices (A/B/C style) when the options are enumerable. Omit choices for open-ended questions.",
      "Ask one focused question at a time. Do not bundle multiple questions.",
      "After receiving an answer, decide whether further clarification is needed or proceed with the task.",
    ],
    parameters: AskUserQuestionParams,
    execute: async (toolCallId, params, signal, onUpdate, ctx) => {
      const { question, choices, placeholder, defaultValue } = params;

      let answer: string | undefined;

      if (choices && choices.length > 0) {
        const withDirect = choices.includes(DIRECT_INPUT_OPTION)
          ? choices
          : [...choices, DIRECT_INPUT_OPTION];

        answer = await ctx.ui.select(question, withDirect, { signal });

        if (answer === DIRECT_INPUT_OPTION) {
          answer = await ctx.ui.input(question, placeholder || defaultValue, {
            signal,
          });
        }
      } else {
        answer = await ctx.ui.input(question, placeholder || defaultValue, {
          signal,
        });
      }

      if (answer === undefined) {
        return {
          content: [{ type: "text", text: "User cancelled the question." }],
          details: undefined,
        };
      }

      return {
        content: [{ type: "text", text: answer }],
        details: undefined,
      };
    },
  });

  // ============================================================
  // subagent Tool
  // ============================================================
  // Delegates tasks to specialized agents running as separate
  // pi processes. Supports single, parallel, and chain modes.
  // ============================================================

  const TaskItem = Type.Object({
    agent: Type.String({
      description: "Name of the agent to invoke",
    }),
    task: Type.String({
      description: "Task to delegate to the agent",
    }),
    cwd: Type.Optional(
      Type.String({
        description: "Working directory for the agent process",
      })
    ),
  });

  const ChainItem = Type.Object({
    agent: Type.String({
      description: "Name of the agent to invoke",
    }),
    task: Type.String({
      description:
        "Task with optional {previous} placeholder for prior step output",
    }),
    cwd: Type.Optional(
      Type.String({
        description: "Working directory for the agent process",
      })
    ),
  });

  const SubagentParams = Type.Object({
    agent: Type.Optional(
      Type.String({
        description: "Agent name for single mode execution",
      })
    ),
    task: Type.Optional(
      Type.String({
        description: "Task description for single mode execution",
      })
    ),
    tasks: Type.Optional(
      Type.Array(TaskItem, {
        description:
          "Array of {agent, task} objects for parallel execution (max 8)",
      })
    ),
    chain: Type.Optional(
      Type.Array(ChainItem, {
        description:
          "Array of {agent, task} objects for sequential chaining. Use {previous} in task to reference prior output.",
      })
    ),
    agentScope: Type.Optional(
      Type.Unsafe<"user" | "project" | "both">({
        type: "string",
        enum: ["user", "project", "both"],
        description:
          'Which agent directories to search. "user" = ~/.pi/agent/agents/, "project" = .pi/agents/ in project root. Default: "user".',
        default: "user",
      })
    ),
    cwd: Type.Optional(
      Type.String({
        description: "Working directory for single mode",
      })
    ),
  });

  pi.registerTool({
    name: "subagent",
    label: "Subagent",
    description:
      "Delegate tasks to specialized agents running as separate pi processes. Supports single, parallel, and chain execution modes.",
    promptSnippet:
      "Delegate tasks to specialized agents (single, parallel, or chain mode)",
    promptGuidelines: [
      "Use single mode (agent + task) for one-off investigation or exploration tasks.",
      "Use parallel mode (tasks array) to dispatch multiple independent agents concurrently, e.g. codebase reviewers.",
      "Use chain mode (chain array) for sequential pipelines where each step uses {previous} to reference prior output.",
      "Bundled agents: 'explorer' (codebase investigation), 'worker' (general execution), 'planner' (architecture design), 'plan-worker' (plan step execution), 'plan-validator' (independent task verification), 'plan-compliance' (pre-task precondition check).",
      "For run-plan execution: use 'plan-compliance' for pre-task checks, 'plan-worker' for task implementation, 'plan-validator' for independent validation under information barrier.",
      "For ultraplan reviews: use 'reviewer-feasibility', 'reviewer-architecture', 'reviewer-risk', 'reviewer-dependency', 'reviewer-user-value' in parallel mode.",
      "If the specified agent is not found, the task runs with default pi settings.",
      "Max 8 parallel tasks with 4 concurrent. Chain mode stops on first error.",
    ],
    parameters: SubagentParams,
    execute: async (toolCallId, params, signal, onUpdate, ctx) => {
      const { agent, task, tasks, chain, agentScope, cwd } = params;
      const defaultCwd = ctx.cwd;
      const agents = await discoverAgents(defaultCwd, agentScope || "user", BUNDLED_AGENTS_DIR);
      const findAgent = (name: string) =>
        agents.find((a) => a.name === name);

      // Chain mode
      if (chain && chain.length > 0) {
        const steps = chain.map((s) => ({
          agent: findAgent(s.agent),
          task: s.task,
          cwd: s.cwd,
        }));

        ctx.ui.setStatus("harness", `Chain: 0/${chain.length} steps`);
        const allResults: import("./subagent.js").SubagentResult[] = [];
        let previousOutput = "";

        for (let i = 0; i < steps.length; i++) {
          const step = steps[i];
          ctx.ui.setStatus("harness", `Chain step ${i + 1}/${chain.length}: ${chain[i].agent}`);
          const taskWithContext = step.task.replace(/\{previous\}/g, previousOutput);
          const result = await runSingleAgent(
            step.agent,
            taskWithContext,
            step.cwd || defaultCwd,
            signal,
          );
          allResults.push(result);

          // Emit progress update
          if (onUpdate) {
            const partialSummary = allResults
              .map((r, j) =>
                `## Step ${j + 1}: ${chain[j].agent}\n**Status:** ${r.exitCode === 0 ? "Success" : "Failed"}\n\n${r.output}`,
              )
              .join("\n\n---\n\n");
            onUpdate({
              content: [{ type: "text" as const, text: partialSummary }],
              details: undefined,
            });
          }

          if (result.exitCode !== 0) {
            ctx.ui.setStatus("harness", undefined);
            const summary = allResults
              .map((r, j) =>
                `## Step ${j + 1}: ${chain[j].agent}\n**Status:** ${r.exitCode === 0 ? "Success" : "Failed"}\n\n${r.output}`,
              )
              .join("\n\n---\n\n");
            return {
              content: [{ type: "text" as const, text: `Chain failed at step ${i + 1}: ${result.error}\n\n${summary}` }],
              details: undefined,
            };
          }

          previousOutput = result.output;
          ctx.ui.notify(`[subagent] Chain step ${i + 1}/${chain.length} done: ${chain[i].agent}`, "info");
        }

        ctx.ui.setStatus("harness", undefined);
        const summary = allResults
          .map((r, i) =>
            `## Step ${i + 1}: ${chain[i].agent}\n**Status:** ${r.exitCode === 0 ? "Success" : "Failed"}\n\n${r.output}`,
          )
          .join("\n\n---\n\n");

        return {
          content: [{ type: "text" as const, text: summary }],
          details: undefined,
        };
      }

      // Parallel mode
      if (tasks && tasks.length > 0) {
        const taskItems = tasks.map((t) => ({
          agent: findAgent(t.agent),
          task: t.task,
          cwd: t.cwd,
        }));

        const total = tasks.length;
        let completed = 0;
        ctx.ui.setStatus("harness", `Parallel: 0/${total} agents running...`);

        const results = await mapWithConcurrencyLimit(taskItems, MAX_CONCURRENCY, async (item, index) => {
          const result = await runSingleAgent(
            item.agent,
            item.task,
            item.cwd || defaultCwd,
            signal,
          );
          completed++;
          ctx.ui.setStatus("harness", `Parallel: ${completed}/${total} agents done`);
          ctx.ui.notify(
            `[subagent] ${tasks[index].agent}: ${result.exitCode === 0 ? "done" : "failed"}`,
            result.exitCode === 0 ? "info" : "warning",
          );

          // Emit progress update
          if (onUpdate) {
            onUpdate({
              content: [{ type: "text" as const, text: `${completed}/${total} agents completed` }],
              details: undefined,
            });
          }

          return result;
        });

        ctx.ui.setStatus("harness", undefined);
        const summary = results
          .map(
            (r, i) =>
              `## Agent: ${tasks[i].agent}\n**Task:** ${tasks[i].task}\n**Status:** ${r.exitCode === 0 ? "Success" : "Failed"}\n\n${r.output}`,
          )
          .join("\n\n---\n\n");

        return {
          content: [{ type: "text" as const, text: summary }],
          details: undefined,
        };
      }

      // Single mode
      if (agent && task) {
        const agentConfig = findAgent(agent);
        ctx.ui.setStatus("harness", `Running: ${agent}`);
        const result = await runSingleAgent(
          agentConfig,
          task,
          cwd || defaultCwd,
          signal,
        );
        ctx.ui.setStatus("harness", undefined);

        return {
          content: [
            {
              type: "text" as const,
              text: result.error
                ? `Error: ${result.error}`
                : result.output,
            },
          ],
          details: undefined,
        };
      }

      return {
        content: [
          {
            type: "text" as const,
            text: "Error: Specify either (agent + task) for single mode, tasks for parallel mode, or chain for chain mode.",
          },
        ],
        details: undefined,
      };
    },
  });

  // ============================================================
  // resources_discover: Register engineering-discipline skills
  // ============================================================

  const SKILLS_DIR = join(homedir(), "engineering-discipline", "skills");

  pi.on("resources_discover", async (_event, _ctx) => {
    return {
      skillPaths: [SKILLS_DIR],
    };
  });

  // ============================================================
  // before_agent_start: Inject workflow phase guidance
  // ============================================================

  const PHASE_GUIDANCE: Record<WorkflowPhase, string> = {
    idle: "",
    clarifying: [
      "\n\n## Active Workflow: Clarification",
      "You are in clarification mode. Follow the clarification skill rules strictly:",
      "- Ask ONE question per message using the ask_user_question tool.",
      "- Generate questions and choices dynamically based on context — no predefined templates.",
      "- Use the subagent tool with agent 'explorer' to investigate the codebase in parallel with user Q&A.",
      "- After each answer, update 'what we've established so far' and assess remaining ambiguity.",
      "- When ambiguity is resolved, present a Context Brief with Complexity Assessment.",
      "- Do NOT start implementation. This phase ends with a Context Brief, not code.",
    ].join("\n"),
    planning: [
      "\n\n## Active Workflow: Plan Crafting",
      "You are in plan-crafting mode. Follow the plan-crafting skill rules strictly:",
      "- Write an executable implementation plan from the current context.",
      "- Every step must be executable — no placeholders.",
      "- Use ask_user_question if you need to resolve any remaining ambiguity.",
      "- End with a Self-Review before presenting the plan.",
    ].join("\n"),
    ultraplanning: [
      "\n\n## Active Workflow: Milestone Planning (Ultraplan)",
      "You are in milestone-planning mode. Follow the milestone-planning skill rules strictly:",
      "- Compose a Problem Brief from the current context.",
      "- Dispatch all 5 reviewer agents in parallel using the subagent tool's parallel mode: reviewer-feasibility, reviewer-architecture, reviewer-risk, reviewer-dependency, reviewer-user-value.",
      "- Synthesize all reviewer findings into a milestone DAG.",
      "- Use ask_user_question if you need user input on trade-offs.",
    ].join("\n"),
  };

  // ============================================================
  // tool_call: Log subagent tool invocations
  // ============================================================

  pi.on("tool_call", async (event, ctx) => {
    if (event.toolName === "subagent") {
      const input = event.input as Record<string, unknown>;
      const mode = input.chain
        ? "chain"
        : input.tasks
          ? "parallel"
          : "single";
      const agentNames = input.chain
        ? (input.chain as any[]).map((s: any) => s.agent).join(", ")
        : input.tasks
          ? (input.tasks as any[]).map((t: any) => t.agent).join(", ")
          : (input.agent as string) || "unknown";

      ctx.ui.notify(
        `[subagent] mode=${mode} agents=[${agentNames}]`,
        "info",
      );
    }
  });

  pi.on("before_agent_start", async (event, _ctx) => {
    const guidance = PHASE_GUIDANCE[currentPhase];
    if (!guidance) return;
    return {
      systemPrompt: event.systemPrompt + guidance,
    };
  });

  // ============================================================
  // context: Microcompaction — truncate old tool results
  // ============================================================

  pi.on("context", async (event, _ctx) => {
    const compacted = microcompactMessages(event.messages);
    const changed = compacted.some((msg, i) => msg !== event.messages[i]);
    if (!changed) return;
    return { messages: compacted };
  });

  // ============================================================
  // session_before_compact: Phase-aware custom summarization
  // ============================================================

  pi.on("session_before_compact", async (event, ctx) => {
    const { preparation, signal } = event;
    const { messagesToSummarize, turnPrefixMessages, tokensBefore, firstKeptEntryId, previousSummary } = preparation;

    const model = ctx.model;
    if (!model) {
      ctx.ui.notify("No model available, using default compaction", "warning");
      return;
    }
    const auth = await ctx.modelRegistry.getApiKeyAndHeaders(model);
    if (!auth.ok || !auth.apiKey) {
      ctx.ui.notify("Compaction auth failed, using default compaction", "warning");
      return;
    }

    const allMessages = [...messagesToSummarize, ...turnPrefixMessages];
    if (allMessages.length === 0) return;

    ctx.ui.notify(
      `Custom compaction: summarizing ${allMessages.length} messages (${tokensBefore.toLocaleString()} tokens)...`,
      "info",
    );

    const conversationText = serializeConversation(convertToLlm(allMessages));

    const promptText = getCompactionPrompt(
      currentPhase,
      activeGoalDocument,
      event.customInstructions,
    );

    const previousContext = previousSummary
      ? `\n\nPrevious session summary for context:\n${previousSummary}`
      : "";

    const summaryMessages = [
      {
        role: "user" as const,
        content: [
          {
            type: "text" as const,
            text: `${promptText}${previousContext}\n\n<conversation>\n${conversationText}\n</conversation>`,
          },
        ],
        timestamp: Date.now(),
      },
    ];

    try {
      const response = await complete(
        model,
        { messages: summaryMessages },
        {
          apiKey: auth.apiKey,
          headers: auth.headers,
          maxTokens: 8192,
          signal,
        },
      );

      const summary = response.content
        .filter((c): c is { type: "text"; text: string } => c.type === "text")
        .map((c) => c.text)
        .join("\n");

      if (!summary.trim()) {
        if (!signal.aborted) {
          ctx.ui.notify("Compaction summary was empty, using default", "warning");
        }
        return;
      }

      const formattedSummary = formatCompactSummary(summary);

      return {
        compaction: {
          summary: formattedSummary,
          firstKeptEntryId,
          tokensBefore,
          details: {
            phase: currentPhase,
            activeGoalDocument,
          },
        },
      };
    } catch (error) {
      if (signal.aborted) return;
      const message = error instanceof Error ? error.message : String(error);
      ctx.ui.notify(`Compaction failed: ${message}`, "error");
      return;
    }
  });

  // ============================================================
  // session_compact: Persist state from compaction details
  // ============================================================

  pi.on("session_compact", async (event, _ctx) => {
    if (event.fromExtension && event.compactionEntry.details) {
      const details = event.compactionEntry.details as {
        phase?: string;
        activeGoalDocument?: string | null;
      };
      if (details.phase) currentPhase = details.phase as WorkflowPhase;
      if (details.activeGoalDocument !== undefined) {
        activeGoalDocument = details.activeGoalDocument;
      }
    }
  });

  // ============================================================
  // tool_result: Track active goal document creation
  // ============================================================

  const GOAL_DOC_PATTERN = /^docs\/engineering-discipline\/(context|plans|reviews)\//;

  pi.on("tool_result", async (event, _ctx) => {
    if (currentPhase === "idle") return;

    const toolName = event.toolName;
    if (toolName !== "write" && toolName !== "edit") return;

    // event.input contains the tool's input args; both write and edit use "path"
    const filePath = event.input.path as string | undefined;
    if (!filePath) return;

    const relativePath = filePath.replace(/^.*?docs\/engineering-discipline\//, "docs/engineering-discipline/");
    if (GOAL_DOC_PATTERN.test(relativePath)) {
      activeGoalDocument = relativePath;
      updateState(STATE_FILE, { activeGoalDocument: relativePath }).catch(() => {});
    }
  });

  // ============================================================
  // Commands
  // ============================================================

  pi.registerCommand("clarify", {
    description:
      "Start clarification — the agent asks dynamic questions to resolve ambiguity",
    handler: async (args, ctx) => {
      const topic = args?.trim() || "";
      const start = await ctx.ui.confirm(
        "Start Clarification",
        "The agent will ask you questions one at a time to clarify your request.\nIt will also explore the codebase in parallel.\n\nProceed?"
      );
      if (!start) return;

      currentPhase = "clarifying";
      activeGoalDocument = null;
      updateState(STATE_FILE, { phase: "clarifying", activeGoalDocument: null }).catch(() => {});
      ctx.ui.setStatus("harness", "Clarification in progress...");

      const prompt = topic
        ? `The user wants to clarify the following request: "${topic}"\n\nBegin the clarification process. Follow the clarification skill rules. Ask ONE question using the ask_user_question tool. Use the subagent tool with agent 'explorer' to investigate relevant parts of the codebase in parallel.`
        : `The user wants to start a clarification session for their current task.\n\nBegin the clarification process. Follow the clarification skill rules. Ask ONE question using the ask_user_question tool to understand what the user wants to accomplish. Use the subagent tool with agent 'explorer' to investigate the codebase in parallel.`;

      pi.sendUserMessage(prompt);
    },
  });

  pi.registerCommand("plan", {
    description:
      "Generate an implementation plan — the agent follows plan-crafting skill rules",
    handler: async (args, ctx) => {
      const ok = await ctx.ui.confirm(
        "Start Plan Crafting",
        "The agent will create an executable implementation plan based on current context.\n\nProceed?"
      );
      if (!ok) return;

      currentPhase = "planning";
      updateState(STATE_FILE, { phase: "planning" }).catch(() => {});
      ctx.ui.setStatus("harness", "Plan crafting in progress...");

      const topic = args?.trim() || "";
      const prompt = topic
        ? `Create an executable implementation plan for: "${topic}"\n\nFollow the plan-crafting skill rules. If a Context Brief exists from a previous clarification, use it as input. If not, use the ask_user_question tool to confirm goal, scope, and tech stack before writing the plan.`
        : `Create an executable implementation plan for the current task.\n\nFollow the plan-crafting skill rules. If a Context Brief exists from a previous clarification, use it as input. If not, use the ask_user_question tool to confirm goal, scope, and tech stack before writing the plan.`;

      pi.sendUserMessage(prompt);
    },
  });

  pi.registerCommand("ultraplan", {
    description:
      "Decompose a complex task into milestones — the agent dynamically selects reviewers",
    handler: async (args, ctx) => {
      const confirmed = await ctx.ui.confirm(
        "Start Milestone Planning (Ultraplan)",
        "The agent will:\n1. Compose a Problem Brief\n2. Decide which reviewer perspectives are needed\n3. Dispatch reviewers in parallel\n4. Synthesize a milestone DAG\n\nProceed?"
      );
      if (!confirmed) return;

      currentPhase = "ultraplanning";
      updateState(STATE_FILE, { phase: "ultraplanning" }).catch(() => {});
      ctx.ui.setStatus("harness", "Milestone planning in progress...");

      const topic = args?.trim() || "";
      const prompt = topic
        ? `Decompose the following complex task into milestones: "${topic}"\n\nFollow the milestone-planning skill rules. First compose a Problem Brief. Then dispatch all 5 reviewer agents in parallel using the subagent tool: reviewer-feasibility, reviewer-architecture, reviewer-risk, reviewer-dependency, reviewer-user-value. After all reviewers complete, synthesize their findings into a milestone DAG.`
        : `Decompose the current complex task into milestones.\n\nFollow the milestone-planning skill rules. First compose a Problem Brief from the current context. Then dispatch all 5 reviewer agents in parallel using the subagent tool: reviewer-feasibility, reviewer-architecture, reviewer-risk, reviewer-dependency, reviewer-user-value. After all reviewers complete, synthesize their findings into a milestone DAG.`;

      pi.sendUserMessage(prompt);
    },
  });

  // ============================================================
  // /ask — manual test command for ask_user_question
  // ============================================================

  pi.registerCommand("ask", {
    description: "Ask the user a question (for testing the ask_user_question tool)",
    handler: async (args, ctx) => {
      const question = await ctx.ui.input(
        "Enter a question",
        args || "What would you like to know?"
      );
      if (!question) return;

      const choicesStr = await ctx.ui.input(
        "Enter comma-separated choices (leave empty for free text)",
        ""
      );
      const choices = choicesStr
        ? choicesStr.split(",").map((s) => s.trim()).filter(Boolean)
        : undefined;

      let answer: string | undefined;
      if (choices && choices.length > 0) {
        answer = await ctx.ui.select(question, choices);
      } else {
        answer = await ctx.ui.input(question);
      }

      if (answer !== undefined) {
        ctx.ui.notify(`Answer: ${answer}`, "info");
      }
    },
  });

  // ============================================================
  // /reset-phase — reset workflow phase to idle
  // ============================================================

  pi.registerCommand("reset-phase", {
    description: "Reset the workflow phase to idle (clears clarify/plan/ultraplan mode)",
    handler: async (_args, ctx) => {
      currentPhase = "idle";
      activeGoalDocument = null;
      updateState(STATE_FILE, { phase: "idle", activeGoalDocument: null }).catch(() => {});
      ctx.ui.setStatus("harness", undefined);
      ctx.ui.notify("Workflow phase reset to idle.", "info");
    },
  });

  // ============================================================
  // Session start notification
  // ============================================================

  pi.on("session_start", async (_event, ctx) => {
    const saved = await loadState(STATE_FILE);
    currentPhase = saved.phase;
    activeGoalDocument = saved.activeGoalDocument;

    ctx.ui.notify(
      "Agentic Harness loaded: /clarify, /plan, /ultraplan, /ask, /reset-phase",
      "info"
    );
  });
}
